#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
Bundler.require(:default, :development)

require_relative '../lib/init'

opts = Trollop::options do
  opt :quier, "Quiet mode"
  opt :debug, "Debug mode"
  opt :download, "Automatically download best (first) match"
  opt :query, "Query to perform", :type => :string, :required => true
  opt :category, "Category", :type => :string, :required => true
end

# TODO: Validate category as either tv or movie

$logger.level = :off if opts[:quiet]
$logger.level = :debug if opts[:debug]

searches = []

Configuration.get['providers'].each do |name, options|
  require File.join($APP_ROOT, 'lib', 'providers', "#{name}")
  provider_module = Providers.const_get(name.capitalize.gsub(/_(.{1})/) { |m| m[1].upcase })
  searches << Thread.new { provider_module.const_get('Search').new(opts[:query], opts[:category], opts[:download], options) }
end

searches.each { |w| w.join }